[[GMT]]
arch = "x86_64"
git-tree-sha1 = "78172096e39edbb7f6d956ae4f58bb83bb4a27da"
libc = "glibc"
os = "linux"

    [[GMT.download]]
    sha256 = "5d145733f534df7fdafac0ca1bbda13554cbf3b5f23ff131843ba69882cf039f"
    url = "https://github.com/joa-quim/GMT_jll/releases/download/taga/GMT.v6.4.0.x86_64-w64-mingw32.tar.gz"
